#!/usr/bin/perl

use LWP::Simple;
use HTML::Parser;
use Data::Dumper;

my $url = shift @ARGV;
die "No URL specified on command line." unless (defined $url);
my $content = get($url); #put site html in $content.
die "get failed" if (!defined $content); 

# create parser object
my $parser = HTML::Parser->new(api_version => 3, start_h => [\&startTag, 'tag, attr'], end_h=>[\&endTag, 'tag'], text_h=>[\&textElem, 'text']);
#parse object.
$parser->parse($content);

sub startTag
{
    my ($tag, $attrHash) = @_;
    print "TAG: $tag \n";
    print "ATTR HASH: ", Dumper $attrHash, "\n";
}

sub endTag
{
    my $tag = shift;
    print "END TAG: $tag \n";
}

sub textElem
{
    my $text = shift;
    print "TEXT: $text \n";
}
